services:
  - type: web
    name: your-app-name
    env: node
    buildCommand: npm install express express-handlebars mongoose bcrypt express-session fs path connect-mongodb-session cookie-parser
    startCommand: node app.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://mrtnandya:QelTswFYEYyKPEVo@topnotch.tqmsmks.mongodb.net/restaurant-review-db
      - key: PORT
        value: 3000
